# -*- coding: utf-8 -*-
"""Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMS97IyWIlnC0oM_ySlllC9bxxe-sDEx
"""

import numpy as np
import pandas as pd

file_path = "/content/orders_realistic.csv"

df = pd.read_csv(file_path)

#  the 'order_date' column is in datetime format
df['order_date'] = pd.to_datetime(df['order_date'])

# Compute the total revenue generated by the online store for each month
df['year_month'] = df['order_date'].dt.to_period('M')
monthly_revenue = df.groupby('year_month').apply(lambda x: (x['product_price'] * x['quantity']).sum()).reset_index(name='total_revenue')
print("Total Revenue by Month:")
print(monthly_revenue)

# Compute the total revenue generated by each product
product_revenue = df.groupby('product_name').apply(lambda x: (x['product_price'] * x['quantity']).sum()).reset_index(name='total_revenue')
print("\nTotal Revenue by Product:")
print(product_revenue)

# Compute the total revenue generated by each customer
customer_revenue = df.groupby('customer_id').apply(lambda x: (x['product_price'] * x['quantity']).sum()).reset_index(name='total_revenue')
print("\nTotal Revenue by Customer:")
print(customer_revenue)

# Identify the top 10 customers by revenue generated
top_10_customers = customer_revenue.sort_values(by='total_revenue', ascending=False).head(10)
print("\nTop 10 Customers by Revenue:")
print(top_10_customers)

# Optionally, we can save these results to CSV files
monthly_revenue.to_csv('monthly_revenue.csv', index=False)
product_revenue.to_csv('product_revenue.csv', index=False)
customer_revenue.to_csv('customer_revenue.csv', index=False)
top_10_customers.to_csv('top_10_customers.csv', index=False)

